apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dash
  namespace: lucasmaia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dash-container
          image: cleifson/monitoring-dashboard:12
          ports:
            - containerPort: 52011
          env:
            - name: REDIS_HOST
              value: "192.168.121.187"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_OUTPUT_KEY
              valueFrom:
                configMapKeyRef:
                  name: outputkey
                  key: REDIS_OUTPUT_KEY
